### ISSUE TITLE
Update the review a PR guideline for the feature/resourcepage challenge.

### ISSUE THREAD

**Issue by Emmanuel-Dominic** [CodeYourFuture/tech-products-demo#35]
## Steps to reproduce

- Review the "Review a PR" task 

NB REQUIREMENT: 
- Update the **README.md** file to include NB: It is important to inform the developers not to raise the pull request to the upstream repository.

- Adding a `pull_request.md` file within the **"Review a PR"** folder on the upstream/origin main branch to address a specific need for copying the desription for the "Review a PR" pull request.

## Expected behaviour

- For instructions on creating a pull request to the origin repository with the feature/resourcepage branch, the developer should be able to know that the pull_request shouldn't be raised to the upstream repository.

- For this challenge, the actual pull request template `pull_request.md` can be found in the main branch under the "Review a PR" folder for clear guidelines added to the **README.md** file and also to avoid reviewing comments on this specific file in the created pull request.

## Actual behaviour
- A `pull_request.md` file appears in the feature/resourcepage branch, which has raised comments since it does not relate to the implementation of the task of viewing a single resource.

- The **README.md** file isn't specific if the pull request should be raised on the upstream or origin.

- The **README.md** file isn't specific on where to find the `pull_request.md` file resulting to the use of the `.githubPULL_REQUEST_TEMPLATE.md` to raise this specific pull request for the challenge.

**Comment by textbook** [comment]
Guidance has been updated in 910e141, hopefully that will be sufficient
